name: Release

on:
  workflow_call:
    inputs:
      semantic_version:
        description: "The Semantic Release version to use"
        type: string
        required: false
    secrets:
      SEMANTIC_RELEASE_TOKEN:
        description: |
          A GitHub token with push access to the repo. If the repo which
          contains the calling workflow does not have protected branches,
          the default `GITHUB_TOKEN` is sufficient.
        required: true
  # For this repo's own releases:
  push:
    branches: [main]
    paths: [".github/workflows/*"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run Semantic-Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: ${{ inputs.semantic_version }}
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
        env:
          # The GITHUB_TOKEN value provided depends on the event type:
          #   On push events to own repo, use the default GITHUB_TOKEN.
          #   On workflow_call events, use the SEMANTIC_RELEASE_TOKEN secret.
          GITHUB_TOKEN: >-
            ${{ github.repository == 'Nerdware-LLC/reusable-action-workflows' &&
                secrets.GITHUB_TOKEN ||
                secrets.SEMANTIC_RELEASE_TOKEN }}
