name: Upload Build to S3

# Runs `npm run build` and uploads the resultant package to an S3 bucket.

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env-vars:
        description: |
          Arbitrary environment variables for the build, provided as a
          space-separated list of key-value pairs (e.g., "FOO=bar BAZ=qux").
          All env-vars are masked before usage.
        type: string
        required: false
      node-version:
        description: |
          The NodeJS version to use. If this input is not provided, the version
          specified in .nvmrc will be used if available — as a final fallback,
          the version specified in the package.json "engines.node" field will
          be used.
        type: string
        required: false
      node-version-file:
        description: The path to the file containing the NodeJS version to use.
        type: string
        required: false
      dist-dirname:
        description: The name of the directory containing the build output.
        type: string
        required: false
        default: "dist"
      s3-sync-command-params:
        description: |
          The options to use with the `aws s3 sync` operation. sync command docs:
          https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html#options
        type: string
        required: false
        default: "--acl bucket-owner-full-control --sse AES256"

    secrets:
      OIDC_GITHUB_ROLE_ARN:
        description: "The ARN of the AWS IAM Role for the GitHub OpenID Connect provider"
        required: true
      S3_BUCKET_REGION:
        description: "The AWS region in which the target S3 bucket is located."
        required: true
      S3_UPLOAD_PATH:
        description: |
          Where to upload the resultant build. This must include the bucket name, and
          may optionally contain a subdirectory path (e.g., "my_foo_bucket/production").
          Do NOT end this value with a trailing slash.
        required: true
      env-vars:
        description: |
          Arbitrary environment variables for the build, provided as a
          space-separated list of key-value pairs (e.g., "FOO=bar BAZ=qux").
          All env-vars are masked before usage.
        required: false

defaults:
  run:
    shell: bash

jobs:
  build_and_upload:
    name: Build & Upload
    runs-on: ubuntu-latest

    # permissions required to use aws-actions/configure-aws-credentials
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE_ARN }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      - name: Build & Upload to S3
        run: |
          # PARSE, MASK, AND EXPORT ENV VARS
          for env_var_kv_pair in ${{ inputs.env-vars }} ${{ secrets.env-vars }}; do
            read -r key value <<< "${env_var_kv_pair/=/ }"
            echo "::add-mask::$key"
            export $key="$value"
          done

          npm ci --include=dev

          npm run build

          # ENSURE AWS CLI ARGS DO NOT CONTAIN LEADING/TRAILING WHITESPACE:

          dist_dirname="$( tr -d ' ' <<< "${{ inputs.dist-dirname }}" )"
          s3_upload_path="$( tr -d ' ' <<< "${{ secrets.S3_UPLOAD_PATH }}" )"

          aws s3 sync "./$dist_dirname" \
            "s3://$s3_upload_path" \
            $( echo ${{ inputs.s3-sync-command-params }} )
